baseURL = 'https://karci.cl/'
languageCode = 'es-cl'
title = 'Karci'
theme = 'ananke'
resourceDir = "../resources"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 3                  # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

[params]
text_color = ""
author = ""
favicon = ""
site_logo = "/images/logo_cropped.jpg"
description = "Karci"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3
